# Generated by Django 2.1.5 on 2019-02-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_communities', '0007_remove_community_circle'),
        ('kongo_posts', '0014_auto_20181215_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='kongo_communities.Community'),
        ),
    ]
