# Generated by Django 2.2 on 2019-05-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_communities', '0025_auto_20190516_1229'),
        ('kongo_moderation', '0002_auto_20190517_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatedobject',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_objects', to='kongo_communities.Community'),
        ),
    ]
