# Generated by Django 2.1.3 on 2018-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_follows', '0007_remove_follow_list'),
        ('kongo_lists', '0002_auto_20181023_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='follows',
            field=models.ManyToManyField(related_name='lists', to='kongo_follows.Follow'),
        ),
    ]
