# Generated by Django 2.2b1 on 2019-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_circles', '0008_auto_20190401_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='connections',
            field=models.ManyToManyField(db_index=True, related_name='circles', to='kongo_connections.Connection'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='posts',
            field=models.ManyToManyField(db_index=True, related_name='circles', to='kongo_posts.Post'),
        ),
    ]
