# Generated by Django 2.2 on 2019-04-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_connections', '0013_auto_20190414_1953'),
        ('kongo_circles', '0012_auto_20190414_2013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectioncircle',
            unique_together={('connection', 'circle')},
        ),
    ]
