# Generated by Django 2.2.16 on 2025-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_circles', '0014_auto_20200120_1600'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='connectioncircle',
            name='kongo_ci_connect_da1cd9_idx',
        ),
        migrations.AddIndex(
            model_name='connectioncircle',
            index=models.Index(fields=['connection', 'circle'], name='kongo_circl_connect_2084c5_idx'),
        ),
    ]
