# Generated by Django 2.2.16 on 2025-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_communities', '0033_auto_20191209_1337'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='kongo_co_communi_bdd180_idx',
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='kongo_co_communi_ca0147_idx',
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='kongo_co_communi_59b23c_idx',
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'user'], name='kongo_commu_communi_a8e6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'user', 'is_administrator'], name='kongo_commu_communi_9af451_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'user', 'is_moderator'], name='kongo_commu_communi_1d7034_idx'),
        ),
    ]
