# Generated by Django 2.1.5 on 2019-02-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_auth', '0016_auto_20190107_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilebadge',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofilebadge',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='kongo_auth.UserProfile'),
            preserve_default=False,
        ),
    ]
