# Generated by Django 2.2.2 on 2019-06-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_common', '0013_language'),
        ('kongo_auth', '0039_auto_20190605_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kongo_common.Language'),
        ),
    ]
