# Generated by Django 2.2.16 on 2025-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_auth', '0053_auto_20200510_1634'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userblock',
            name='kongo_au_blocked_3369e6_idx',
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked_user', 'blocker'], name='kongo_auth__blocked_ad47f6_idx'),
        ),
    ]
