# Generated by Django 2.2.16 on 2025-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongo_follows', '0009_auto_20200510_1634'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='follow',
            name='kongo_fo_followe_a71981_idx',
        ),
        migrations.RemoveIndex(
            model_name='followrequest',
            name='kongo_fo_creator_6d37cf_idx',
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed_user', 'user'], name='kongo_follo_followe_bd5277_idx'),
        ),
        migrations.AddIndex(
            model_name='followrequest',
            index=models.Index(fields=['creator', 'target_user'], name='kongo_follo_creator_2e1b79_idx'),
        ),
    ]
